name: Create and publish a Docker image

on:
  workflow_call:
    inputs:
      package:
        description: 'Which Dockerfile package to build'
        required: true
        type: string
      dry-run:
        type: boolean
        required: true
  workflow_dispatch:
    inputs:
      package:
        description: 'Which Dockerfile package to build'
        required: true
        type: string
      dry-run:
        type: boolean
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Log in to the Container registry
        if: ${{ ! inputs.dry-run }}
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Get version
        id: version
        working-directory: "docker/${{ inputs.package }}"
        shell: bash
        run: echo "version=$(cat this.version)" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          file: "docker/${{ inputs.package }}/Dockerfile"
          push: ${{ ! inputs.dry-run }}
          tags:
            - "ghcr.io/org-zpr/${{ inputs.package }}:latest"
            - "ghcr.io/org-zpr/${{ inputs.package }}:${{ steps.version.outputs.version }}"
