name: Create and publish a Docker image

on:
  push:
    branches: ['main']
    paths:
      - 'docker/Dockerfile'
      - '.github/workflows/build-docker.yml'
  pull_request:
    paths:
      - 'docker/Dockerfile'
      - '.github/workflows/build-docker.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          file: ./docker/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/org-zpr/38f3bb925e5e
