name: Containerized Rust Build & Test

on:
  workflow_call:
    inputs:
      path:
        required: false
        type: string
        default: './'
      name:
        required: true
        type: string
      setup:
        required: false
        type: string
    secrets:
      ZPR_CICD_RO_TOKEN:
        required: true

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  build-and-test:
    name: "Build & test"
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    container:
      image: docker://ghcr.io/org-zpr/38f3bb925e5e:latest
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Prepare Rust
      timeout-minutes: 5
      run: rustup default stable

    - name: Setup Git credentials
      timeout-minutes: 1
      run: |
        echo 'echo $ZPR_CICD_RO_TOKEN' > "$HOME/.git-askpass"
        chmod +x "$HOME/.git-askpass"
        echo "GIT_ASKPASS=$HOME/.git-askpass" >> "$GITHUB_ENV"

    - name: Run Setup
      if: ${{ inputs.setup != '' }}
      timeout-minutes: 5
      run: ${{ inputs.setup }}

    - name: Build ${{ inputs.name }}
      id: build
      timeout-minutes: 5
      env:
        ZPR_CICD_RO_TOKEN: ${{ secrets.ZPR_CICD_RO_TOKEN }}
      run: cargo build --verbose

    - name: Test ${{ inputs.name }}
      timeout-minutes: 5
      env:
        ZPR_CICD_RO_TOKEN: ${{ secrets.ZPR_CICD_RO_TOKEN }}
      run: cargo test --verbose

    - name: Check format
      if: ${{ ! cancelled()  }}
      timeout-minutes: 5
      run: cargo fmt --check

    - name: Check warnings
      if: ${{ ! cancelled() && steps.build.outcome == 'success' }}
      timeout-minutes: 5
      run: cargo rustc -- -D warnings

    - name: Check test warnings
      if: ${{ ! cancelled() && steps.build.outcome == 'success' }}
      timeout-minutes: 5
      run: cargo rustc --tests -- -D warnings
