name: Tag Release

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  make-tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create Tag
      shell: bash
      run: |
        version="$(cat this.version)"

        if git tag --list | grep -q "$version"; then
          echo "Tag already exists.  Nothing to do."
        else
          git tag "$version"
          git push origin "$version"
        fi
